apiVersion: v1
kind: Service
metadata:
  name: chaos-exporter
  namespace: monitoring
  labels:
    app: chaos-exporter # ServiceMonitorがこれを見つける
spec:
  ports:
    - name: metrics # ポートに名前をつけるのが重要
      port: 8082
      targetPort: 8082
  selector:
    app: chaos-exporter
